from __future__ import annotations

import json
from collections import Counter
from pathlib import Path

from ccmigrate.models import Conversation
from ccmigrate.util import write_jsonl


def export_all(conversations: list[Conversation], out: Path, max_message_chars: int = 8000) -> dict[str, str]:
    out.mkdir(parents=True, exist_ok=True)
    paths = {
        "markdown": export_markdown(conversations, out / "conversations.md", max_message_chars),
        "jsonl": export_transcript_jsonl(conversations, out / "conversations.jsonl"),
    }
    for name, content in provider_memory_files(conversations).items():
        path = out / name
        path.write_text(content, encoding="utf-8")
        paths[name] = str(path)
    return paths


def export_markdown(
    conversations: list[Conversation],
    path: Path,
    max_message_chars: int = 8000,
) -> str:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# ccmigrate conversation archive", ""]
    lines.extend(inventory_lines(conversations))
    lines.append("")
    for conv in conversations:
        lines.extend(
            [
                "---",
                "",
                f"## {safe_title(conv)}",
                "",
                f"- Provider: `{conv.provider}`",
                f"- Project: `{conv.project or 'unknown'}`",
                f"- Created: `{conv.created_at or 'unknown'}`",
                f"- Updated: `{conv.updated_at or 'unknown'}`",
                f"- Source: `{conv.source_path}`",
                "",
            ]
        )
        for message in conv.messages:
            content = truncate(message.content, max_message_chars)
            lines.extend([f"### {message.role}", "", content, ""])
        for tool_call in conv.tool_calls:
            lines.extend(
                [
                    f"### tool: {tool_call.name}",
                    "",
                    "```json",
                    json.dumps(tool_call.input, indent=2, ensure_ascii=False),
                    "```",
                    "",
                ]
            )
            if tool_call.result:
                lines.extend(["Result:", "", truncate(tool_call.result, max_message_chars), ""])
        if conv.plan_content:
            lines.extend(["### plan", "", truncate(conv.plan_content, max_message_chars), ""])
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    return str(path)


def export_transcript_jsonl(conversations: list[Conversation], path: Path) -> str:
    rows = []
    for conv in conversations:
        for index, message in enumerate(conv.messages):
            rows.append(
                {
                    "type": "text",
                    "conversation_id": conv.id,
                    "provider": conv.provider,
                    "project": conv.project,
                    "title": conv.title,
                    "message_index": index,
                    "message_id": message.id,
                    "role": message.role,
                    "content": message.content,
                    "created_at": message.created_at,
                }
            )
        for index, tool_call in enumerate(conv.tool_calls):
            rows.append(
                {
                    "type": "tool_call",
                    "conversation_id": conv.id,
                    "provider": conv.provider,
                    "project": conv.project,
                    "title": conv.title,
                    "tool_index": index,
                    "tool_call_id": tool_call.id,
                    "name": tool_call.name,
                    "input": tool_call.input,
                    "result": tool_call.result,
                    "created_at": tool_call.created_at,
                }
            )
    write_jsonl(path, rows)
    return str(path)


def provider_memory_files(conversations: list[Conversation]) -> dict[str, str]:
    agents = memory_markdown(conversations, "AGENTS.md")
    claude = "@AGENTS.md\n\n## Claude Code\n\nUse the shared AGENTS.md memory generated by ccmigrate.\n"
    opencode = agents
    return {
        "AGENTS.md": agents,
        "CLAUDE.md": claude,
        "OPENCODE.md": opencode,
    }


def memory_markdown(conversations: list[Conversation], filename: str) -> str:
    lines = [
        f"# {filename}",
        "",
        "## Shared Agent Context",
        "",
        "This file was generated by ccmigrate from local agent chat archives.",
        "Treat it as portable context, not as a complete source of truth.",
        "",
    ]
    lines.extend(inventory_lines(conversations))
    lines.extend(["", "## Recent Conversation Index", ""])
    for conv in sorted(conversations, key=lambda item: item.updated_at or "", reverse=True)[:50]:
        first_user = next((msg.content for msg in conv.messages if msg.role == "user"), "")
        lines.append(
            f"- `{conv.provider}` `{conv.project or 'unknown'}` `{conv.updated_at or 'unknown'}`: "
            f"{truncate(first_user.replace(chr(10), ' '), 220)}"
        )
    lines.extend(
        [
            "",
            "## Archive",
            "",
            "Full normalized transcripts live in `.ccmigrate/conversations.jsonl`.",
            "Use `ccmigrate export --format markdown` to regenerate a readable transcript bundle.",
        ]
    )
    return "\n".join(lines).rstrip() + "\n"


def inventory_lines(conversations: list[Conversation]) -> list[str]:
    provider_counts = Counter(conv.provider for conv in conversations)
    project_counts = Counter(conv.project or "unknown" for conv in conversations)
    lines = [
        "## Inventory",
        "",
        f"- Conversations: {len(conversations)}",
        f"- Messages: {sum(len(conv.messages) for conv in conversations)}",
        f"- Tool calls: {sum(len(conv.tool_calls) for conv in conversations)}",
        f"- Turns: {sum(conv.turn_count for conv in conversations)}",
        f"- Providers: {', '.join(f'{name}={count}' for name, count in sorted(provider_counts.items())) or 'none'}",
        "",
        "## Projects",
        "",
    ]
    for project, count in project_counts.most_common(30):
        lines.append(f"- `{project}`: {count} conversations")
    return lines


def safe_title(conv: Conversation) -> str:
    return conv.title or f"{conv.provider}:{conv.id}"


def truncate(value: str, limit: int) -> str:
    if len(value) <= limit:
        return value
    return value[: max(0, limit - 20)].rstrip() + "\n\n[truncated by ccmigrate]"
