from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from ccmigrate.dump import write_thread_dump
from ccmigrate.models import Conversation, Message, ToolCall
from ccmigrate.util import write_json


def default_handoff_dir(project: str | None = None) -> Path:
    base = Path(project).expanduser() if project else Path.cwd()
    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    return base / ".ccmigrate" / "handoffs" / stamp


def write_handoff(
    conversations: list[Conversation],
    out: Path,
    *,
    recent_messages: int = 24,
    max_chars: int = 24000,
    include_dump: bool = True,
    make_zip: bool = False,
    include_shards: bool = True,
    shard_chars: int = 50000,
    note: str | None = None,
) -> dict[str, Any]:
    out.mkdir(parents=True, exist_ok=True)
    handoff_path = out / "HANDOFF.md"
    prompt_path = out / "codex-prompt.txt"
    selected = conversations[:1]
    handoff_path.write_text(
        render_handoff(selected, recent_messages=recent_messages, max_chars=max_chars, note=note),
        encoding="utf-8",
    )
    prompt_path.write_text(render_codex_prompt(handoff_path), encoding="utf-8")

    manifest: dict[str, Any] = {
        "created_at": datetime.now(timezone.utc).isoformat(),
        "conversation_count": len(selected),
        "message_count": sum(len(conv.messages) for conv in selected),
        "tool_call_count": sum(len(conv.tool_calls) for conv in selected),
        "handoff": str(handoff_path),
        "codex_prompt": str(prompt_path),
        "strategy": "compact_handoff",
    }
    if include_dump:
        dump_dir = out / "full-dump"
        dump_manifest = write_thread_dump(selected, dump_dir, make_zip=make_zip, note=note)
        manifest["full_dump"] = dump_manifest.get("dump", {})
        manifest["full_archive"] = dump_manifest.get("archive")
    if include_shards:
        shard_manifest = write_search_shards(selected, out / "search-shards", shard_chars=shard_chars)
        manifest["search_shards"] = shard_manifest
    write_json(out / "manifest.json", manifest)
    return manifest


def render_codex_prompt(handoff_path: Path) -> str:
    return (
        f"Read {handoff_path} first. Use it as the compact continuation context for this task. "
        "Do not resume or load the full raw transcript. If you need a specific older detail, "
        "search the sibling search-shards directory with rg and open only the matching shard. "
        "Then continue from the Next Steps section."
    )


def render_handoff(
    conversations: list[Conversation],
    *,
    recent_messages: int,
    max_chars: int,
    note: str | None,
) -> str:
    if not conversations:
        return "# Agent Handoff\n\nNo conversations matched.\n"

    conv = conversations[0]
    budget = TextBudget(max_chars)
    lines: list[str] = [
        "# Agent Handoff",
        "",
        "This is a compact continuation file generated by ccmigrate.",
        "Use it instead of resuming a huge native transcript.",
        "",
        "## Source Thread",
        "",
        f"- Provider: `{conv.provider}`",
        f"- Project: `{conv.project or 'unknown'}`",
        f"- Title: `{conv.title or conv.id}`",
        f"- Conversation id: `{conv.id}`",
        f"- Native session id: `{conv.metadata.get('session_id') or 'unknown'}`",
        f"- Updated: `{conv.updated_at or 'unknown'}`",
        f"- Messages: {len(conv.messages)}",
        f"- Tool calls: {len(conv.tool_calls)}",
        f"- Source path: `{conv.source_path}`",
        "",
    ]
    if note:
        lines.extend(["## User Note", "", budget.take(note.strip()), ""])

    first_user = first_message(conv.messages, "user")
    last_user = last_message(conv.messages, "user")
    last_assistant = last_message(conv.messages, "assistant")
    lines.extend(["## Task Snapshot", ""])
    if first_user:
        lines.extend(["Initial ask:", "", budget.take(blockquote(first_user.content, 1800)), ""])
    if last_user and last_user is not first_user:
        lines.extend(["Most recent user direction:", "", budget.take(blockquote(last_user.content, 2400)), ""])
    if last_assistant:
        lines.extend(["Most recent assistant response:", "", budget.take(blockquote(last_assistant.content, 2400)), ""])

    if conv.plan_content:
        lines.extend(["## Plan Content", "", budget.take(conv.plan_content, 4000), ""])

    lines.extend(["## Recent Conversation Tail", ""])
    for message in conv.messages[-recent_messages:]:
        if not budget.remaining:
            break
        content = compact_text(message.content)
        lines.extend([f"### {message.role} `{message.created_at or 'unknown'}`", "", budget.take(content, 1800), ""])

    tool_summary = summarize_tools(conv.tool_calls)
    if tool_summary:
        lines.extend(["## Tool Activity Summary", "", *tool_summary, ""])

    lines.extend(
        [
            "## Next Steps For The New Agent",
            "",
            "- Treat this file as the working memory, not as a complete transcript.",
            "- Start by checking current repository state with `git status --short --branch`.",
            "- Read project files directly instead of trusting stale transcript claims.",
            "- Do not load the full raw transcript into context.",
            "- For older transcript details, search `search-shards/` with `rg` and open only matching shard files.",
            "- Only inspect `full-dump/threads.md` as a last resort for specific missing details.",
            "- Continue from the most recent user direction above.",
            "",
        ]
    )
    if not budget.remaining:
        lines.extend(["## Truncation", "", "This handoff hit its character budget. Use the full dump for older details.", ""])
    return "\n".join(lines).rstrip() + "\n"


class TextBudget:
    def __init__(self, total: int):
        self.remaining = max(0, total)

    def take(self, value: str, limit: int | None = None) -> str:
        if self.remaining <= 0:
            return ""
        value = value.strip()
        allowed = self.remaining if limit is None else min(self.remaining, limit)
        if len(value) > allowed:
            result = value[: max(0, allowed - 32)].rstrip() + "\n\n[truncated]"
        else:
            result = value
        self.remaining -= len(result)
        return result


def first_message(messages: list[Message], role: str) -> Message | None:
    return next((message for message in messages if message.role == role), None)


def last_message(messages: list[Message], role: str) -> Message | None:
    return next((message for message in reversed(messages) if message.role == role), None)


def compact_text(value: str) -> str:
    value = re.sub(r"\n{3,}", "\n\n", value.strip())
    return value


def blockquote(value: str, limit: int) -> str:
    value = compact_text(value)
    if len(value) > limit:
        value = value[: max(0, limit - 16)].rstrip() + "\n[truncated]"
    return "\n".join(f"> {line}" if line else ">" for line in value.splitlines())


def summarize_tools(tool_calls: list[ToolCall]) -> list[str]:
    if not tool_calls:
        return []
    counts: dict[str, int] = {}
    for call in tool_calls:
        counts[call.name] = counts.get(call.name, 0) + 1
    lines = ["Tool counts:"]
    for name, count in sorted(counts.items(), key=lambda item: (-item[1], item[0])):
        lines.append(f"- `{name}`: {count}")
    recent = tool_calls[-12:]
    if recent:
        lines.extend(["", "Recent tool calls:"])
        for call in recent:
            subject = call.input.get("command") or call.input.get("file_path") or call.input.get("path") or ""
            lines.append(f"- `{call.name}` `{call.created_at or 'unknown'}` {str(subject)[:180]}")
    return lines


def write_search_shards(
    conversations: list[Conversation],
    out: Path,
    *,
    shard_chars: int,
) -> dict[str, Any]:
    out.mkdir(parents=True, exist_ok=True)
    index_lines = [
        "# Search Shards",
        "",
        "These files split the large source transcript into grep-friendly pieces.",
        "Do not load all shards into an agent context. Search first, then open only relevant files.",
        "",
        "Example:",
        "",
        "```bash",
        "rg -n \"scorecard|fallback|endpoint\" search-shards",
        "```",
        "",
    ]
    files: list[dict[str, Any]] = []
    for conv in conversations:
        chunks = list(conversation_chunks(conv, shard_chars=max(1000, shard_chars)))
        for idx, chunk in enumerate(chunks, start=1):
            path = out / f"{conv.provider}-{conv.id}-part-{idx:04d}.md"
            path.write_text(chunk, encoding="utf-8")
            files.append({"path": str(path), "chars": len(chunk), "conversation_id": conv.id, "part": idx})
            index_lines.append(f"- `{path.name}`: {len(chunk)} chars")
    (out / "INDEX.md").write_text("\n".join(index_lines).rstrip() + "\n", encoding="utf-8")
    return {
        "directory": str(out),
        "index": str(out / "INDEX.md"),
        "file_count": len(files),
        "files": files,
    }


def conversation_chunks(conv: Conversation, *, shard_chars: int):
    header = "\n".join(
        [
            f"# Transcript shard for {conv.provider}:{conv.id}",
            "",
            f"- Project: `{conv.project or 'unknown'}`",
            f"- Title: `{conv.title or conv.id}`",
            f"- Updated: `{conv.updated_at or 'unknown'}`",
            "",
        ]
    )
    current = [header]
    current_len = len(header)

    def flush():
        nonlocal current, current_len
        if len(current) > 1:
            text = "\n".join(current).rstrip() + "\n"
            current = [header]
            current_len = len(header)
            return text
        return None

    for i, message in enumerate(conv.messages, start=1):
        block = "\n".join(
            [
                f"## Message {i}: {message.role} `{message.created_at or 'unknown'}`",
                "",
                message.content.strip(),
                "",
            ]
        )
        if current_len + len(block) > shard_chars:
            flushed = flush()
            if flushed:
                yield flushed
        current.append(block)
        current_len += len(block)

    if conv.tool_calls:
        block_lines = ["# Tool Calls", ""]
        for i, call in enumerate(conv.tool_calls, start=1):
            subject = call.input.get("command") or call.input.get("file_path") or call.input.get("path") or ""
            block_lines.append(f"- {i}. `{call.name}` `{call.created_at or 'unknown'}` {str(subject)[:300]}")
        block = "\n".join(block_lines) + "\n"
        if current_len + len(block) > shard_chars:
            flushed = flush()
            if flushed:
                yield flushed
        current.append(block)

    flushed = flush()
    if flushed:
        yield flushed
